### ISSUE TITLE
ex04: main 関数がないと動かない

### ISSUE THREAD

**Issue by unstoppa61e** [nafuka11/go-piscine-go-tester#3]
問題文には

> 関数 calculationStr を作成してください。

とありますので、main 関数が入っていない状態で動く仕様の方が良いように思いましたが、いかがでしょうか？

**Comment by nafuka11** [comment]
提案いただき、ありがとうございます！

問題文には、

> 以下のmain関数と標準出力を満たすような関数calculationStr を作成してください。

とあったため、main 関数と calculationStr 関数、2つ作成すると解釈しておりました。

どちらとも解釈できてしまうため、
READMEに、「ex04, ex05は main 関数がないと出力のテストはできない」と記載しようと思います。

main 関数がない場合、gofmtの検証のみして、出力のテストをスキップしようと思います。
